defaults:
  - base_config
  - override triangulation: pairs_from_poses_low-res
  - override dino_feature: low-res
  - override decomp/transformer/postprocess_test: inference_cvpr
  - override decomp/transformer/saving: test_autorecon_cvpr
  - _self_

sfm_mode: idr2colmap
idr2colmap:
  save_dirname: sfm_from_idr
triangulation:
  reference_sfm_reldir: sfm_from_idr
decomp:
  sfm_preprocess:
    use_cache: True
    online: True
    visualize: True
  transformer:
    saving:
      save_dirname: auto-deocomp_sfm-transformer_cvpr
